// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibatduxkhhabedlglqvo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImliYXRkdXhraGhhYmVkbGdscXZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNzQ4MjksImV4cCI6MjA1OTc1MDgyOX0.i1ZaBDaDBlAxs_9wVigC5Y2NGxF1aEvMu3lAL5ZYClw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);